Repository iMicknl/python-overkiz-api, pull requests merged in 2020-08, with the labels that each got.

#40 Add release drafter
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-drafter.yml
Labels: Meta: Exclude From Changelog, enhancement

#41 Handle 'Attempt to decode JSON with unexpected mimetype: ' exceptions
  pyhoma/client.py
  pyhoma/exceptions.py
Labels: fix

#42 Bump version to v0.3.5
  pyproject.toml
Labels: Meta: Exclude From Changelog

#43 Relogin when disconnected
  .github/workflows/main.yaml
  .idea/misc.xml
  .idea/python-tahoma-api.iml
  .pre-commit-config.yaml
  README.md
  poetry.lock
  pyhoma/client.py
  pyproject.toml
  setup.cfg
Labels: breaking, enhancement

#44 Add refresh states command
  README.md
  pyhoma/client.py
Labels: feature
