Repository iMicknl/python-overkiz-api, pull requests merged in 2021-11, with the labels that each got.

#234 Add push subscription created event
  pyhoma/enums.py
Labels: enhancement

#235 Add product type 7 (group)
  pyhoma/enums.py
Labels: bug

#228 Add Overkiz State, Command, CommandParameter enums
  pyhoma/enums.py
  pyhoma/enums/__init__.py
  pyhoma/enums/command.py
  pyhoma/enums/execution.py
  pyhoma/enums/gateway.py
  pyhoma/enums/general.py
  pyhoma/enums/state.py
  pyhoma/enums/ui.py
Labels: breaking, feature

#249 Add more event enums
  pyhoma/enums/general.py
Labels: enhancement
