Repository iMicknl/python-overkiz-api, pull requests merged in 2021-09, with the labels that each got.

#176 Refresh listener id when invalid or missing
  pyhoma/client.py
  pyhoma/exceptions.py
Labels: bug

#183 Add more labels to release drafter
  .github/pr-labeler.yml
  .github/release-drafter.yml
Labels: enhancement, ci

#177 Use attrs for classes
  .pre-commit-config.yaml
  poetry.lock
  pyhoma/models.py
  pyproject.toml
  tests/test_client.py
Labels: enhancement

#184 Remove qualified_name for Device
  pyhoma/models.py
Labels: bug

#185 Add Nexity Rail Din
  pyhoma/enums.py
Labels: bug
