Repository iMicknl/python-overkiz-api, pull requests merged in 2022-01, with the labels that each got.

#298 Move from warrant to warrant-lite
  poetry.lock
  pyoverkiz/client.py
  pyproject.toml
Labels: enhancement

#294 Apply new attrs decorators
  pyoverkiz/models.py
Labels: enhancement

#295 Fix CI
  .github/workflows/main.yaml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: bug

#299 Comply to PEP 0561
  pyoverkiz/models.py
  pyoverkiz/py.typed
  pyproject.toml
Labels: enhancement

#302 Update device model
  pyoverkiz/enums/ui.py
  pyoverkiz/models.py
Labels: bug

#304 Fix UIWidget enums
  pyoverkiz/enums/ui.py
Labels: bug

#305 Move casting to event listener and add OverkizStateType
  pyoverkiz/models.py
  pyoverkiz/types.py
  tests/test_client.py
Labels: enhancement

#312 Make last update time optional + add tests
  pyoverkiz/models.py
  tests/fixtures/setup/setup_tahoma_be.json
  tests/test_client.py
Labels: bug

#324 Add diagnostics endpoint
  pyoverkiz/client.py
  pyoverkiz/models.py
  pyoverkiz/obfuscate.py
  pyoverkiz/types.py
  utils/mask_fixtures.py
Labels: enhancement

#323 Add new cozytouch setup sample
  tests/fixtures/setup/setup_cozytouch_2.json
  tests/fixtures/setup/setup_cozytouch_3.json
  tests/fixtures/setup/setup_hi_kumo_2.json
  tests/test_client.py
Labels: testing

#337 set gateway_id attribute in Gateway
  pyoverkiz/models.py
Labels: bug

#338 Add Cozytouch V2 to Gateway enums
  pyoverkiz/enums/gateway.py
  tests/fixtures/setup/setup_cozytouch_v2.json
  tests/test_client.py
Labels: feature

#336 Add protocol property to Device model
  .pylintrc
  pyoverkiz/enums/__init__.py
  pyoverkiz/enums/protocol.py
  pyoverkiz/models.py
Labels: enhancement

#333 Move to Somfy OAuth as access method for Somfy Europe
  pyoverkiz/client.py
  pyoverkiz/const.py
  pyoverkiz/exceptions.py
  setup.cfg
Labels: enhancement

#341 Add hlrrwifi protocol
  pyoverkiz/enums/protocol.py
Labels: bug

#343 Add rtn protocol
  pyoverkiz/enums/protocol.py
Labels: bug

#344 Fix Nexity login and add extra Nexity setup test
  pyoverkiz/client.py
  tests/fixtures/setup/setup_nexity_2.json
  tests/test_client.py
Labels: bug

#340 Obfuscate label in logging
  pyoverkiz/models.py
Labels: enhancement

#349 Set last_update_time as optional for Location
  pyoverkiz/models.py
Labels: bug

#346 Refresh token before using listener id
  pyoverkiz/client.py
Labels: bug
