Repository iMicknl/python-overkiz-api, pull requests merged in 2022-02, with the labels that each got.

#363 Add Somfy Connectivity Kit to Gateway enums
  pyoverkiz/enums/gateway.py
  tests/test_enums.py
Labels: enhancement

#362 Extend enums for various devices (mainly alarm)
  pyoverkiz/enums/command.py
  pyoverkiz/enums/state.py
Labels: enhancement

#365 Add missing state enums for DHWP
  pyoverkiz/enums/state.py
Labels: feature

#367 Add commands to DHWP_TYPE_CV4E_IO
  pyoverkiz/enums/command.py
Labels: feature

#374 Improve exceptions and exception handling (TooManyConcurrent and Bearer+Session)
  pyoverkiz/client.py
  pyoverkiz/exceptions.py
Labels: enhancement

#377 Add GatewayFirmwareUpdatedEvent to event enums
  pyoverkiz/enums/general.py
Labels: enhancement

#379 Extend event enums
  pyoverkiz/const.py
  pyoverkiz/enums/general.py
Labels: enhancement

#381 Update enums for Alarm Control Panel
  pyoverkiz/enums/command.py
Labels: enhancement

#383 Add lowspeed command parameter
  pyoverkiz/enums/command.py
Labels: enhancement

#384 Add extra RTS commands
  pyoverkiz/enums/command.py
Labels: enhancement

#385 Move 2 commands from params to commands
  pyoverkiz/enums/command.py
Labels: enhancement

#388 Fix typo in SET_VENTILATION_MODE
  pyoverkiz/enums/command.py
Labels: bug, breaking

#390 Fix model for Rexel gateways
  pyoverkiz/models.py
Labels: bug
